{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "231a7897",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd, json, os, re, time\n",
    "from concurrent.futures import ThreadPoolExecutor, as_completed\n",
    "import urllib.request, urllib.error\n",
    "\n",
    "import sys\n",
    "CSV  = sys.argv[1] if len(sys.argv) > 1 else 'resume_jd_pairs_sampled.csv'\n",
    "OUT  = sys.argv[2] if len(sys.argv) > 2 else 'scores.jsonl'\n",
    "CKPT = OUT + '.done_rows.txt'\n",
    "\n",
    "RS = ['resume_EDUCATION','resume_EXPERIENCE','resume_PROJECTS','resume_SKILLS']\n",
    "JS = ['jd_job_title','jd_minimum_requirements','jd_preferred_qualifications','jd_other_information']\n",
    "\n",
    "df = pd.read_csv(CSV).fillna('')\n",
    "\n",
    "PROMPT = \"\"\"You are an expert technical recruiter scoring how well a resume section matches a job-description section. Score each of the 16 section pairs from 1.0 to 10.0 (one decimal allowed).\n",
    "\n",
    "Scoring guidance:\n",
    "- 9-10: directly and strongly relevant; clear evidence the resume section satisfies what the JD section asks.\n",
    "- 7-8: solid relevance with good overlap.\n",
    "- 5-6: partial / adjacent relevance. IMPORTANT: if the candidate has the SAME job ROLE but a DIFFERENT tech stack (e.g. full-stack dev with Spring experience vs a role demanding Django or .NET), score 5-6, NOT low. Transferable role/skills still count.\n",
    "- 3-4: weak/tangential relevance.\n",
    "- 1-2: essentially unrelated.\n",
    "Never score 0. A mismatched stack within the same role family is a 5-6, not a 1.\n",
    "\n",
    "Judge each pair on the actual content provided. A job_title pair scores how well the resume section fits that title. minimum_requirements/preferred_qualifications score how well the resume section satisfies those requirements. other_information is usually lower-signal (logistics, company info) unless it states real requirements.\n",
    "\n",
    "RESUME SECTIONS:\n",
    "[resume_EDUCATION]\n",
    "{r_edu}\n",
    "\n",
    "[resume_EXPERIENCE]\n",
    "{r_exp}\n",
    "\n",
    "[resume_PROJECTS]\n",
    "{r_proj}\n",
    "\n",
    "[resume_SKILLS]\n",
    "{r_skills}\n",
    "\n",
    "JD SECTIONS:\n",
    "[jd_job_title]\n",
    "{j_title}\n",
    "\n",
    "[jd_minimum_requirements]\n",
    "{j_min}\n",
    "\n",
    "[jd_preferred_qualifications]\n",
    "{j_pref}\n",
    "\n",
    "[jd_other_information]\n",
    "{j_other}\n",
    "\n",
    "Return ONLY a JSON object, no preamble, no markdown. Keys are \"<resume_section>|<jd_section>\" for all 16 combos, values are floats. Exact format:\n",
    "{{\"resume_EDUCATION|jd_job_title\":x,\"resume_EDUCATION|jd_minimum_requirements\":x,\"resume_EDUCATION|jd_preferred_qualifications\":x,\"resume_EDUCATION|jd_other_information\":x,\"resume_EXPERIENCE|jd_job_title\":x,\"resume_EXPERIENCE|jd_minimum_requirements\":x,\"resume_EXPERIENCE|jd_preferred_qualifications\":x,\"resume_EXPERIENCE|jd_other_information\":x,\"resume_PROJECTS|jd_job_title\":x,\"resume_PROJECTS|jd_minimum_requirements\":x,\"resume_PROJECTS|jd_preferred_qualifications\":x,\"resume_PROJECTS|jd_other_information\":x,\"resume_SKILLS|jd_job_title\":x,\"resume_SKILLS|jd_minimum_requirements\":x,\"resume_SKILLS|jd_preferred_qualifications\":x,\"resume_SKILLS|jd_other_information\":x}}\"\"\"\n",
    "\n",
    "def trunc(s, n=4000):\n",
    "    s = str(s)\n",
    "    return s if len(s) <= n else s[:n]\n",
    "\n",
    "def call_api(prompt):\n",
    "    body = json.dumps({\n",
    "        \"model\": \"claude-sonnet-4-6\",\n",
    "        \"max_tokens\": 1000,\n",
    "        \"messages\": [{\"role\": \"user\", \"content\": prompt}]\n",
    "    }).encode()\n",
    "    req = urllib.request.Request(\"https://api.anthropic.com/v1/messages\", data=body,\n",
    "        headers={\"Content-Type\": \"application/json\",\n",
    "                 \"x-api-key\": os.environ[\"ANTHROPIC_API_KEY\"],\n",
    "                 \"anthropic-version\": \"2023-06-01\"})\n",
    "    with urllib.request.urlopen(req, timeout=120) as resp:\n",
    "        data = json.loads(resp.read())\n",
    "    txt = \"\".join(b.get(\"text\",\"\") for b in data.get(\"content\",[]) if b.get(\"type\")==\"text\")\n",
    "    txt = re.sub(r'```json|```', '', txt).strip()\n",
    "    return json.loads(txt)\n",
    "\n",
    "def process_row(idx):\n",
    "    row = df.iloc[idx]\n",
    "    prompt = PROMPT.format(\n",
    "        r_edu=trunc(row['resume_EDUCATION']), r_exp=trunc(row['resume_EXPERIENCE']),\n",
    "        r_proj=trunc(row['resume_PROJECTS']), r_skills=trunc(row['resume_SKILLS']),\n",
    "        j_title=trunc(row['jd_job_title']), j_min=trunc(row['jd_minimum_requirements']),\n",
    "        j_pref=trunc(row['jd_preferred_qualifications']), j_other=trunc(row['jd_other_information']))\n",
    "    last = None\n",
    "    for attempt in range(4):\n",
    "        try:\n",
    "            scores = call_api(prompt)\n",
    "            recs = []\n",
    "            for r in RS:\n",
    "                for j in JS:\n",
    "                    sc = float(scores[f\"{r}|{j}\"])\n",
    "                    sc = max(1.0, min(10.0, sc))\n",
    "                    recs.append({\n",
    "                        \"resume_id\": row['resume_resume_id'],\n",
    "                        \"jd_id\": row['jd_job_id'],\n",
    "                        \"resume_section_name\": r,\n",
    "                        \"jd_section_name\": j,\n",
    "                        \"resume_section_content\": row[r],\n",
    "                        \"jd_section_content\": row[j],\n",
    "                        \"matching_score\": sc})\n",
    "            return idx, recs\n",
    "        except Exception as e:\n",
    "            last = e\n",
    "            time.sleep(2*(attempt+1))\n",
    "    return idx, last\n",
    "\n",
    "def main():\n",
    "  done = set()\n",
    "  if os.path.exists(CKPT):\n",
    "    done = set(int(x) for x in open(CKPT).read().split() if x.strip())\n",
    "  todo = [i for i in range(len(df)) if i not in done]\n",
    "  print(f\"todo {len(todo)} / {len(df)}\")\n",
    "\n",
    "  fout = open(OUT, 'a')\n",
    "  fckpt = open(CKPT, 'a')\n",
    "  t0 = time.time()\n",
    "  ok = err = 0\n",
    "  with ThreadPoolExecutor(max_workers=12) as ex:\n",
    "      futs = {ex.submit(process_row, i): i for i in todo}\n",
    "      for n, fut in enumerate(as_completed(futs), 1):\n",
    "          idx, res = fut.result()\n",
    "          if isinstance(res, list):\n",
    "              for rec in res: fout.write(json.dumps(rec, ensure_ascii=False)+\"\\n\")\n",
    "              fckpt.write(f\"{idx}\\n\"); ok += 1\n",
    "          else:\n",
    "              err += 1\n",
    "              print(f\"row {idx} FAILED: {res}\")\n",
    "          if n % 100 == 0:\n",
    "              fout.flush(); fckpt.flush()\n",
    "              el = time.time()-t0\n",
    "              print(f\"{n}/{len(todo)} ok={ok} err={err} {el:.0f}s rate={n/el:.1f}/s\")\n",
    "  fout.flush(); fckpt.flush(); fout.close(); fckpt.close()\n",
    "  print(f\"DONE ok={ok} err={err} time={time.time()-t0:.0f}s\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
